project:
  type: website
  output-dir: docs

website:
  description: "Krish Suraparaju's personal website and blog."
  site-url: https://csuraparaju.github.io/
  title: "Krish's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/csuraparaju
      - icon: linkedin
        href: https://www.linkedin.com/in/krish-suraparaju/
format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: false
    css: styles.css



