project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/csuraparaju
      - icon: linkedin
        href: https://www.linkedin.com/in/krish-suraparaju/
format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: false
    css: styles.css



